version: '3'

services:
        viberr:
                build:
                        context: ./src
                        args:
                                - DEPLOYMENT_ENVIRONMENT
                command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
                environment:
                        - DEPLOYMENT_ENVIRONEMENT
                        - DJANGO_SECRET_KEY
                volumes:
                        - ./src:/src
                working_dir: /src
                ports:
                        - 8000:8000
                depends_on:
                        - postgres

        postgres:
                image: postgres:latest
                environment:
                        - POSTGRES_DATABASE
                        - POSTGRES_USER
                        - POSTGRES_PASSWORD
                volumes:
                        - ~/PostgresData/viberr/postgres_data:/var/lib/postgresql/data

