version: '3'

services:
    web:
        build: ./src
        command: gunicorn viberr.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ./src/:/src
        expose:
            - 8000
        env_file:
            - ./.env
        depends_on:
            - postgres
    postgres:
        image: postgres:12.0
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    nginx:
        image: nginx:1.17.4
        ports:
            - 8000:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - web
volumes:
    postgres_data:

